In [4]:
from keras.applications.resnet50 import ResNet50
from keras.preprocessing import image
from keras.applications.resnet50 import preprocess_input, decode_predictions
import numpy as np

import os
import time

In [8]:
curr_dir = os.getcwd()
print(curr_dir)

/Users/Mihai/Documents/Project_5152cv/derma_diagnosis


In [9]:
dict_images={
    'names':['ISIC_0033919.jpg','ISIC_0027242.jpg','ISIC_0030581.jpg','ISIC_0033920.jpg',
             'ISIC_0027243.jpg','ISIC_0030582.jpg','ISIC_0033921.jpg']}

path = curr_dir+'/resnet50_best.h5'

In [7]:
model = ResNet50(weights='imagenet')
#img_path = curr_dir+'/Elephant.jpg'

for name in dict_images.get('names'):
    print(name)
    img_path = curr_dir+'/data/ISIC2018_Task3_Training_Input/'+name
    img = image.load_img(img_path, target_size=(224, 224))
    x = image.img_to_array(img)
    x = np.expand_dims(x, axis=0)
    x = preprocess_input(x)

    preds = model.predict(x)
    # decode the results into a list of tuples (class, description, probability)
    # (one such list for each sample in the batch)
    print('Predicted:', decode_predictions(preds, top=3)[0])
    # Predicted: [(u'n02504013', u'Indian_elephant', 0.82658225), (u'n01871265', u'tusker', 0.1122357), (u'n02504458', u'African_elephant', 0.061040461)]


ValueError: Dimension 1 in both shapes must be equal, but are 1000 and 3 for 'Assign_645' (op: 'Assign') with input shapes: [2048,1000], [2048,3].

In [10]:
from keras.models import load_model
import time

In [19]:
def predict(img_path, model):
    img = image.load_img(img_path, target_size=(224, 224))
    x = image.img_to_array(img)
    x = np.expand_dims(x, axis=0)
    preds = model.predict(x)
    return preds


In [21]:
t0 = time.time()
model = load_model(path)
t1 = time.time()
print('Loaded in:', t1-t0)

Loaded in: 22.990717887878418


In [26]:
benign_dir='/data/small/test/benign/'
malign_dir='/data/small/test/malign/'
#samples = [ISIC_0000014.jpg']
directory1 = curr_dir+benign_dir+'ISIC_0000014.jpg'
directory2 = curr_dir+malign_dir+'ISIC_0000002.jpg'
directory3 = curr_dir+malign_dir+'ISIC_0001102.jpg'

In [31]:
print('Generating predictions on image:', directory3)
preds = predict(directory3, model)
print(preds)

Generating predictions on image: /Users/Mihai/Documents/Project_5152cv/derma_diagnosis/data/small/test/malign/ISIC_0001102.jpg
[[0.8401168 0.1598832]]


In [32]:
print('Generating predictions on image:', directory1)
preds = predict(directory1, model)
print(preds)

Generating predictions on image: /Users/Mihai/Documents/Project_5152cv/derma_diagnosis/data/small/test/benign/ISIC_0000014.jpg
[[0.5893425  0.41065747]]


In [33]:
print('Generating predictions on image:', directory2)
preds = predict(directory2, model)
print(preds)

Generating predictions on image: /Users/Mihai/Documents/Project_5152cv/derma_diagnosis/data/small/test/malign/ISIC_0000002.jpg
[[0.6724333  0.32756662]]
